#!/usr/bin/env sh
#
# Clone gilbertsoft/infrastructure-opsone-dba from github to user home
# Copyright (C) 2019  Gilbertsoft
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

n=$(readlink -f ${0})
if [ "$(basename ${0})" = "install" ]; then
    # Create tmp copy to prevent update errors
    cp -p ${n} ${n}.exec
    chmod +x ${n}.exec
    exec ${n}.exec
else
    # Change directory to user home
    cd ~

    # Check for an existing git repository
    if [ -d ".git" ]; then
        echo "*****************************************************************************"
        echo "* A git repository does already exist, the installer will use the current   *"
        echo "* branch to continue the setup process.                                     *"
        echo "*                                                                           *"
        echo "* If you like to do a fresh installation, run the following command:        *"
        echo "*                                                                           *"
        echo "*  'rm -fr .git && ./installer'                                             *"
        echo "*                                                                           *"
        echo "*****************************************************************************"

        # Reset hard and update
        git reset -q --hard
        git pull -q
    else
        # Clone gilbertsoft/infrastructure-opsone-dba stable branch from github
        git clone -q --depth=1 --branch=stable https://github.com/gilbertsoft/infrastructure-opsone-dba.git tmp/dba

        # Move .git to current directory
        mv tmp/dba/.git .git

        # Delete tmp/dba
        rm -fr tmp/dba
    fi

    # Run setup script
    . ./setup

    # Clean up tmp .exec file
    if [ -f ${n} ]; then
        rm -f ${n}
    fi
fi
