#!/usr/bin/env sh
#
# Install phpMyAdmin
# Copyright (C) 2019  Gilbertsoft
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Delete existing git repository
if [ -d ".git" ]; then
    
fi

# Install gilbertsoft/infrastructure-opsone-dba from github
if [ ! -d ".git" ]; then
    # Install stable version to tmp/dba
    git clone -q --depth=1 --branch=master https://github.com/gilbertsoft/infrastructure-opsone-dba.git tmp/dba

    # Move .git to home
    mv tmp/dba/.git .git

    # Delete tmp/dba
    rm -fr tmp/dba
fi

# Reset to master and update
git reset --hard origin/master
git pull -q origin master

# Run setup script
./setup
