#!/usr/bin/env sh
#
# Install or update phpMyAdmin
# Copyright (C) 2019  Gilbertsoft
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Reset to master
git reset --hard origin/master
git pull

# Create configuration from dist
[ -f "config.inc.php" ] || cp config.dist.inc.php config.inc.php

# Install current version to www-new and link configuration
composer create-project phpmyadmin/phpmyadmin www-new --no-dev
ln -s config.inc.php www-new/config.inc.php

# Backup current version
mv www www-old-`date +%Y%m%d%H%M`

# Go live
mv www-new www

# Test for local changes

echo ""
echo "***************************************************************************"
echo "* Check for local changes, read the following lines to ensure no changes: *"
echo "***************************************************************************"
echo ""

git branch -v
git status

echo ""
echo "***************************************************************************"
echo ""
echo "Installation finished!"
