#!/usr/bin/env sh
#
# Install or update phpMyAdmin
# Copyright (C) 2019  Gilbertsoft
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Create configuration from dist
if [ ! -f "config.inc.php" ]; then
    cp config.dist.inc.php config.inc.php
    sed -i -e "s/add_new_secret_here/`pwgen -s 32 1`/g" config.inc.php
fi

# Install or update phpMyAdmin from github
if [ ! -d "www/.git" ]; then
    # Install stable version to www-new
    git clone -q --depth=1 --branch=STABLE https://github.com/phpmyadmin/phpmyadmin.git www-new

    # Symlink configuration
    ln -rs config.inc.php www-new/config.inc.php

    # Backup current version
    mv www www-old-`date +%Y%m%d%H%M`

    # Go live
    mv www-new www
else
    # Update stable version
    cd www
    git pull -q origin STABLE
    cd ..
fi

# Register cron job
if [ ! -f ".jobregistered" ]; then
    (crontab -l && echo "\t0\t1\t*\t*\t*\t/home/$USER/update >/dev/null") | crontab -
    touch .jobregistered
fi

echo "phpMyAdmin is installed and up to date now!"
