#!/usr/bin/env sh
#
# Setup phpMyAdmin
# Copyright (C) 2019  Gilbertsoft
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Search for an existing www directory
if [ ! -d "www" ]; then
    echo "Error web directory 'www' was not found!"
    exit 1
fi

# Create configuration from dist
if [ ! -f "config.inc.php" ]; then
    cp config.dist.inc.php config.inc.php
    sed -i -e "s/add_new_secret_here/`pwgen -s 32 1`/g" config.inc.php
fi

# Install stable version to www-new
composer create-project --repository-url=https://www.phpmyadmin.net/packages.json --no-dev phpmyadmin/phpmyadmin www-new

# Symlink configuration
ln -rs config.inc.php www-new/config.inc.php

# Backup existing www on first install
if [ ! -f "www/config.inc.php" ]; then
    mv www www-old-`date +%Y%m%d%H%M`
fi

# Go live
mv www-new www

# Register cron job
if [ ! -f ".jobregistered" ]; then
    (crontab -l && echo "\t0\t1\t*\t*\t*\t/home/$USER/update >/dev/null") | crontab -
    touch .jobregistered
fi

echo ""
echo "phpMyAdmin is installed and up to date now!"
