#!/usr/bin/env sh
#
# Update phpMyAdmin
# Copyright (C) 2019  Gilbertsoft
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

n=$(readlink -f ${0})
if [ "$(basename ${0})" == "update" ]; then
    # Create tmp copy to prevent update errors
    cp -p ${n} ${n}.exec
    chmod +x ${n}.exec
    exec ${n}.exec
else
    # Reset and update
    git reset -q --hard
    git pull -q

    # Run setup script
    . ./setup

    # Clean up tmp .exec file
    if [ -f ${n} ]; then
        rm -f ${n}
    fi
fi
